# Generated by Django 5.0.1 on 2024-02-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_rename_groups_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chosen_answer',
            new_name='chosen_group',
        ),
    ]
