# Generated by Django 5.0.1 on 2024-02-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chosen_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.group'),
        ),
    ]
