# Generated by Django 5.0.1 on 2024-02-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num_competences_displayed',
            field=models.IntegerField(default=5),
        ),
    ]
